name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
        bash rancher-save-images.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rancher-images-tar
        path: rancher-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm rancher-images.tar.gz
